### ISSUE TITLE
how to visualize the results

### ISSUE THREAD

**Issue by hyaihjq** [wlguan/Stronger-yolo-pytorch#12]

**Comment by wlguan** [comment]
@hyaihjq  Hi, the visualization code is [here](https://github.com/wlguan/Stronger-yolo-pytorch/blob/master/evaluator/voceval.py#L39-L39). You may jump into the source file for more details.

**Comment by simon-rob** [comment]
@hyaihjq 

This will get you started:


```
from models import *
from trainers import *
import json
from yacscfg import _C as cfg
import os
from torch import optim
import argparse
import numpy as np
import torch
from utils.nms_utils import torch_nms
from utils.visualize import visualize_boxes
import cv2


def img_preprocess(image, target_shape, keepratio=True):
  h_target, w_target = target_shape
  h_org, w_org, _ = image.shape

  image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB).astype(np.float32)
  if not keepratio:
    ratio_w = w_target / w_org
    ratio_h = h_target / h_org
    image = cv2.resize(image, target_shape, interpolation=cv2.INTER_LINEAR) / 255.0
    return image

  resize_ratio = min(1.0 * w_target / w_org, 1.0 * h_target / h_org)
  resize_w = int(resize_ratio * w_org)
  resize_h = int(resize_ratio * h_org)
  image_resized = cv2.resize(image, (resize_w, resize_h))
  image_paded = np.full((h_target, w_target, 3), 128.0)
  dw = int((w_target - resize_w) / 2)
  dh = int((h_target - resize_h) / 2)
  image_paded[dh:resize_h + dh, dw:resize_w + dw, :] = image_resized
  image = image_paded / 255.0

  return image

def _postprocess(pred_bbox, test_input_size, org_img_shape):
     if hasattr(args, 'MODEL') and args.MODEL.boxloss == 'KL':
        pred_coor = pred_bbox[:, 0:4]
        pred_vari = pred_bbox[:, 4:8]
        pred_vari = torch.exp(pred_vari)
        pred_conf = pred_bbox[:, 8]
        pred_prob = pred_bbox[:, 9:]
     else:
        pred_coor = pred_bbox[:, 0:4]
        pred_conf = pred_bbox[:, 4]
        pred_prob = pred_bbox[:, 5:]
      
     org_h, org_w = org_img_shape

     resize_ratio = min(1.0 * test_input_size / org_w, 1.0 * test_input_size / org_h)
     dw = (test_input_size - resize_ratio * org_w) / 2
     dh = (test_input_size - resize_ratio * org_h) / 2
     pred_coor[:, 0::2] = 1.0 * (pred_coor[:, 0::2] - dw) / resize_ratio
     pred_coor[:, 1::2] = 1.0 * (pred_coor[:, 1::2] - dh) / resize_ratio
     x1,y1,x2,y2=torch.split(pred_coor,[1,1,1,1],dim=1)
     x1,y1=torch.max(x1,torch.zeros_like(x1)),torch.max(y1,torch.zeros_like(y1))
     x2,y2=torch.min(x2,torch.ones_like(x2)*(org_w-1)),torch.min(y2,torch.ones_like(y2)*(org_h-1))
     pred_coor=torch.cat([x1,y1,x2,y2],dim=-1)

     # ***********************
     if pred_prob.shape[-1]==0:
        pred_prob = torch.ones((pred_prob.shape[0], 1)).cuda()
     # ***********************
     scores = pred_conf.unsqueeze(-1) * pred_prob

     bboxes = torch.cat([pred_coor, scores], dim=-1)
     
     if hasattr(args, 'MODEL') and args.MODEL.boxloss == 'KL' and args.EVAL.varvote:
        return bboxes, pred_vari
     else:
        return bboxes,None


def detect_image(args, model, image):

   orishape = image.shape[:2]
   originimg=image
   
   image=img_preprocess(image, (args.EXPER.test_size, args.EXPER.test_size), True)

   input=torch.from_numpy(image).cuda().float().permute(2,0,1).unsqueeze(0)

   with torch.no_grad():
       output = model(input)
       bbox,bboxvari = _postprocess(output[0], args.EXPER.test_size, orishape)
       nms_boxes, nms_scores, nms_labels = torch_nms(args.EVAL, bbox, variance=bboxvari)

       if nms_boxes is not None:
          originimg = visualize_boxes(image=originimg, boxes=nms_boxes.cpu().numpy(), labels=nms_labels.cpu().numpy(), probs=nms_scores.cpu().numpy(), class_labels=args.MODEL.LABEL)

   return originimg


def main(args, imgpath):
    gpus=[str(g) for g in args.devices]
    os.environ['CUDA_VISIBLE_DEVICES'] = ','.join(gpus)

    image = cv2.imread(imgpath)

    model = eval(cfg.MODEL.modeltype)(cfg=args.MODEL).cuda()

    load_path = './checkpoints/{}/'.format(args.EXPER.experiment_name)

    ckptfile = torch.load(os.path.join(load_path, 'checkpoint-{}.pth'.format(args.EXPER.resume)))
    model.load_state_dict(ckptfile['state_dict'])

    best_mAP = ckptfile['metric']
    print("Loaded checkpoint - mAP:", best_mAP)

    model.eval()
    image = detect_image(args, model, image)

    cv2.imshow("Image", image)
    cv2.waitKey(0)
    cv2.imwrite('detect_result.jpg', image)



if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="DEMO configuration")
    parser.add_argument(
        "--config-file",
        default='configs/strongerv3.yaml'
    )
    parser.add_argument('--image', help='image file', default='b1c9c847-3bda4659.jpg', type=str)


    parser.add_argument(
        "opts",
        help="Modify config options using the command-line",
        default=None,
        nargs=argparse.REMAINDER,
    )
    args = parser.parse_args()
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    cfg.freeze()
    main(args=cfg, imgpath=args.image)
```

use:

python3 demo.py --config-file configs/strongerv3.yaml  EXPER.experiment_name strongerv3 EXPER.resume best

**Comment by hyaihjq** [comment]
> @hyaihjq
> 
> This will get you started:
> 
> ```
> from models import *
> from trainers import *
> import json
> from yacscfg import _C as cfg
> import os
> from torch import optim
> import argparse
> import numpy as np
> import torch
> from utils.nms_utils import torch_nms
> from utils.visualize import visualize_boxes
> import cv2
> 
> 
> def img_preprocess(image, target_shape, keepratio=True):
>   h_target, w_target = target_shape
>   h_org, w_org, _ = image.shape
> 
>   image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB).astype(np.float32)
>   if not keepratio:
>     ratio_w = w_target / w_org
>     ratio_h = h_target / h_org
>     image = cv2.resize(image, target_shape, interpolation=cv2.INTER_LINEAR) / 255.0
>     return image
> 
>   resize_ratio = min(1.0 * w_target / w_org, 1.0 * h_target / h_org)
>   resize_w = int(resize_ratio * w_org)
>   resize_h = int(resize_ratio * h_org)
>   image_resized = cv2.resize(image, (resize_w, resize_h))
>   image_paded = np.full((h_target, w_target, 3), 128.0)
>   dw = int((w_target - resize_w) / 2)
>   dh = int((h_target - resize_h) / 2)
>   image_paded[dh:resize_h + dh, dw:resize_w + dw, :] = image_resized
>   image = image_paded / 255.0
> 
>   return image
> 
> def _postprocess(pred_bbox, test_input_size, org_img_shape):
>      if hasattr(args, 'MODEL') and args.MODEL.boxloss == 'KL':
>         pred_coor = pred_bbox[:, 0:4]
>         pred_vari = pred_bbox[:, 4:8]
>         pred_vari = torch.exp(pred_vari)
>         pred_conf = pred_bbox[:, 8]
>         pred_prob = pred_bbox[:, 9:]
>      else:
>         pred_coor = pred_bbox[:, 0:4]
>         pred_conf = pred_bbox[:, 4]
>         pred_prob = pred_bbox[:, 5:]
>       
>      org_h, org_w = org_img_shape
> 
>      resize_ratio = min(1.0 * test_input_size / org_w, 1.0 * test_input_size / org_h)
>      dw = (test_input_size - resize_ratio * org_w) / 2
>      dh = (test_input_size - resize_ratio * org_h) / 2
>      pred_coor[:, 0::2] = 1.0 * (pred_coor[:, 0::2] - dw) / resize_ratio
>      pred_coor[:, 1::2] = 1.0 * (pred_coor[:, 1::2] - dh) / resize_ratio
>      x1,y1,x2,y2=torch.split(pred_coor,[1,1,1,1],dim=1)
>      x1,y1=torch.max(x1,torch.zeros_like(x1)),torch.max(y1,torch.zeros_like(y1))
>      x2,y2=torch.min(x2,torch.ones_like(x2)*(org_w-1)),torch.min(y2,torch.ones_like(y2)*(org_h-1))
>      pred_coor=torch.cat([x1,y1,x2,y2],dim=-1)
> 
>      # ***********************
>      if pred_prob.shape[-1]==0:
>         pred_prob = torch.ones((pred_prob.shape[0], 1)).cuda()
>      # ***********************
>      scores = pred_conf.unsqueeze(-1) * pred_prob
> 
>      bboxes = torch.cat([pred_coor, scores], dim=-1)
>      
>      if hasattr(args, 'MODEL') and args.MODEL.boxloss == 'KL' and args.EVAL.varvote:
>         return bboxes, pred_vari
>      else:
>         return bboxes,None
> 
> 
> def detect_image(args, model, image):
> 
>    orishape = image.shape[:2]
>    originimg=image
>    
>    image=img_preprocess(image, (args.EXPER.test_size, args.EXPER.test_size), True)
> 
>    input=torch.from_numpy(image).cuda().float().permute(2,0,1).unsqueeze(0)
> 
>    with torch.no_grad():
>        output = model(input)
>        bbox,bboxvari = _postprocess(output[0], args.EXPER.test_size, orishape)
>        nms_boxes, nms_scores, nms_labels = torch_nms(args.EVAL, bbox, variance=bboxvari)
> 
>        if nms_boxes is not None:
>           originimg = visualize_boxes(image=originimg, boxes=nms_boxes.cpu().numpy(), labels=nms_labels.cpu().numpy(), probs=nms_scores.cpu().numpy(), class_labels=args.MODEL.LABEL)
> 
>    return originimg
> 
> 
> def main(args, imgpath):
>     gpus=[str(g) for g in args.devices]
>     os.environ['CUDA_VISIBLE_DEVICES'] = ','.join(gpus)
> 
>     image = cv2.imread(imgpath)
> 
>     model = eval(cfg.MODEL.modeltype)(cfg=args.MODEL).cuda()
> 
>     load_path = './checkpoints/{}/'.format(args.EXPER.experiment_name)
> 
>     ckptfile = torch.load(os.path.join(load_path, 'checkpoint-{}.pth'.format(args.EXPER.resume)))
>     model.load_state_dict(ckptfile['state_dict'])
> 
>     best_mAP = ckptfile['metric']
>     print("Loaded checkpoint - mAP:", best_mAP)
> 
>     model.eval()
>     image = detect_image(args, model, image)
> 
>     cv2.imshow("Image", image)
>     cv2.waitKey(0)
>     cv2.imwrite('detect_result.jpg', image)
> 
> 
> 
> if __name__ == '__main__':
>     parser = argparse.ArgumentParser(description="DEMO configuration")
>     parser.add_argument(
>         "--config-file",
>         default='configs/strongerv3.yaml'
>     )
>     parser.add_argument('--image', help='image file', default='b1c9c847-3bda4659.jpg', type=str)
> 
> 
>     parser.add_argument(
>         "opts",
>         help="Modify config options using the command-line",
>         default=None,
>         nargs=argparse.REMAINDER,
>     )
>     args = parser.parse_args()
>     cfg.merge_from_file(args.config_file)
>     cfg.merge_from_list(args.opts)
>     cfg.freeze()
>     main(args=cfg, imgpath=args.image)
> ```
> 
> use:
> 
> python3 demo.py --config-file configs/strongerv3.yaml EXPER.experiment_name strongerv3 EXPER.resume best
thanks!!!

**Comment by hyaihjq** [comment]
> @hyaihjq Hi, the visualization code is [here](https://github.com/wlguan/Stronger-yolo-pytorch/blob/master/evaluator/voceval.py#L39-L39). You may jump into the source file for more details.

thanks! i have solved it.
