### ISSUE TITLE
Can ASFF model be pruned?

### ISSUE THREAD

**Issue by simon-rob** [wlguan/Stronger-yolo-pytorch#14]
When trying to prune an ASSF model I get the following error:

Traceback (most recent call last):
  File "main_prune.py", line 186, in <module>
    main(args=cfg)
  File "main_prune.py", line 128, in main
    pruner.prune()
  File "/hdd1/Stronger-yolo-pytorch/head/Stronger-yolo-pytorch/pruning/slimming.py", line 89, in prune
    block.clone2module(m0, inputmask)
  File "/hdd1/Stronger-yolo-pytorch/head/Stronger-yolo-pytorch/pruning/Block.py", line 46, in clone2module
    temp = self.statedict[0][:, inputmask.tolist(), :, :]
AttributeError: 'NoneType' object has no attribute 'tolist'

**Comment by wlguan** [comment]
Yes, but you need to add extra graph node to BasePruner. I will do it when I have time.

**Comment by simon-rob** [comment]
> Yes, but you need to add extra graph node to BasePruner. I will do it when I have time.



> When trying to prune an ASSF model I get the following error:
> 
> Traceback (most recent call last):
> File "main_prune.py", line 186, in
> main(args=cfg)
> File "main_prune.py", line 128, in main
> pruner.prune()
> File "/hdd1/Stronger-yolo-pytorch/head/Stronger-yolo-pytorch/pruning/slimming.py", line 89, in prune
> block.clone2module(m0, inputmask)
> File "/hdd1/Stronger-yolo-pytorch/head/Stronger-yolo-pytorch/pruning/Block.py", line 46, in clone2module
> temp = self.statedict[0][:, inputmask.tolist(), :, :]
> AttributeError: 'NoneType' object has no attribute 'tolist'

Any chance you could find some time for this?
