### ISSUE TITLE
the impelement focalloss is true?

### ISSUE THREAD

**Issue by hyaihjq** [wlguan/Stronger-yolo-pytorch#16]

**Comment by wlguan** [comment]
请问你想表达的意思是focalloss的实现是否正确吗？

**Comment by hyaihjq** [comment]
> 请问你想表达的意思是focalloss的实现是否正确吗？

不好意思，我已经看懂了，focalloss除了focalloss函数部分还包括ｌｏｓｓ中的部分。谢谢！！！
