### ISSUE TITLE
Is COCO dataset supported for training now?

### ISSUE THREAD

**Issue by ArsenLuca** [wlguan/Stronger-yolo-pytorch#17]
It seems that training mscoco is not well supported due to the ./dataset/coco.py is not ready.
e.g. self._ids in COCOdataset is null

**Comment by wlguan** [comment]
The small bug is fixed. Pull the latest code and try :)

**Comment by ArsenLuca** [comment]
> The small bug is fixed. Pull the latest code and try :)

Thanks:)
