### ISSUE TITLE
about strongerv3/checkpoint-best.pth

### ISSUE THREAD

**Issue by xiaaxioo** [wlguan/Stronger-yolo-pytorch#18]
Thank you for sharing the repo.

I did not find strongerv3/checkpoint-best.pth in your upload folder.  Could you double check it? 

Thanks!

**Comment by wlguan** [comment]
Sorry, I deleted the ckpt for strongerv3 by mistake before. Just train wth the config file and you will get a similar result.

**Comment by TccccD** [comment]
能不能共享一下这个ckpt，backbone_pretrained: 'checkpoints/mobilenet_v2.pth' ，以及问下如果不用预训练模型，从头开始训练voc也可以达到很高精度吗
