### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tolist'

### ISSUE THREAD

**Issue by ArsenLuca** [wlguan/Stronger-yolo-pytorch#22]
When I prune sparse MobileNetV2-backbone model trained on MSCOCO, it comes up with an error:

```
CB(name=module.backbone.features.18, id=19, numweights=5,inchannel=320,outchannel=1280)
CB(name=module.headslarge.conv0, id=20, numweights=5,inchannel=1280,outchannel=512)
DCB(name=module.headslarge.conv1, id=21, numweights=10,inchannel=512,outchannel=1024)
CB(name=module.headslarge.conv2, id=22, numweights=5,inchannel=1024,outchannel=512)
DCB(name=module.headslarge.conv3, id=23, numweights=10,inchannel=512,outchannel=1024)
CB(name=module.headslarge.conv4, id=24, numweights=5,inchannel=1024,outchannel=512)
DCB(name=module.detlarge.conv5, id=25, numweights=10,inchannel=512,outchannel=1024)
Conv(name=module.detlarge.conv6, id=26, numweights=2,inchannel=1024,outchannel=267)
Traceback (most recent call last):
  File "yolov3_prune.py", line 72, in <module>
    main(args=cfg)
  File "yolov3_prune.py", line 37, in main
    pruner.prune()
  File "/home/xxx/Stronger-yolo-pytorch-master/pruning/slimming.py", line 92, in prune
    block.clone2module(m0, inputmask)
  File "/home/xxx/Stronger-yolo-pytorch-master/pruning/Block.py", line 46, in clone2module
    temp = self.statedict[0][:, inputmask.tolist(), :, :]
AttributeError: 'NoneType' object has no attribute 'tolist'
```

It seems that Conv Class in ./pruning/Block.py has no member outmask, so the inputmask in ./pruning/slimming.py (line 74) is NoneType? 
Is it the problem?@wlguan

**Comment by wlguan** [comment]
@ArsenLuca Hi, did you use the ASFF module? This module is not supported by now.

**Comment by ArsenLuca** [comment]
> @ArsenLuca Hi, did you use the ASFF module? This module is not supported by now.

@wlguan Exactly. But I tried to set ASFF to be False, it still comes up with an error on (CB(name=module.mergelarge.conv7, id=27, numweights=5,inchannel=512,outchannel=256)):

```
CB(name=module.backbone.features.18, id=19, numweights=5,inchannel=320,outchannel=1280)
CB(name=module.headslarge.conv0, id=20, numweights=5,inchannel=1280,outchannel=512)
DCB(name=module.headslarge.conv1, id=21, numweights=10,inchannel=512,outchannel=1024)
CB(name=module.headslarge.conv2, id=22, numweights=5,inchannel=1024,outchannel=512)
DCB(name=module.headslarge.conv3, id=23, numweights=10,inchannel=512,outchannel=1024)
CB(name=module.headslarge.conv4, id=24, numweights=5,inchannel=1024,outchannel=512)
DCB(name=module.detlarge.conv5, id=25, numweights=10,inchannel=512,outchannel=1024)
Conv(name=module.detlarge.conv6, id=26, numweights=2,inchannel=1024,outchannel=267)
CB(name=module.mergelarge.conv7, id=27, numweights=5,inchannel=512,outchannel=256)
Traceback (most recent call last):
  File "yolov3_prune.py", line 72, in <module>
    main(args=cfg)
  File "yolov3_prune.py", line 37, in main
    pruner.prune()
  File "/home/xxx/Stronger-yolo-pytorch-master/pruning/slimming.py", line 91, in prune
    block.clone2module(m0, inputmask)
  File "/home/xxx/Stronger-yolo-pytorch-master/pruning/Block.py", line 46, in clone2module
    temp = self.statedict[0][:, inputmask.tolist(), :, :]
AttributeError: 'NoneType' object has no attribute 'tolist'
```

**Comment by ArsenLuca** [comment]
That is because the layer before CB(name=module.mergelarge.conv7, id=27, numweights=5,inchannel=512,outchannel=256) is a Conv (module.detlarge.conv6), whose outmask is NoneType @wlguan

**Comment by wlguan** [comment]
@ArsenLuca You're right. But I already change the input of mergelarge.conv7 [here ](https://github.com/wlguan/Stronger-yolo-pytorch/blob/master/pruning/BasePruner.py#L37-L38). Did you try the strongerv3_prune.yaml experiment? It should be OK.

**Comment by ArsenLuca** [comment]
> @ArsenLuca You're right. But I already change the input of mergelarge.conv7 [here ](https://github.com/wlguan/Stronger-yolo-pytorch/blob/master/pruning/BasePruner.py#L37-L38). Did you try the strongerv3_prune.yaml experiment? It should be OK.

@wlguan 
I find the problem. It's because I trained the yolov3 model by Multiple GPUs. So DataParallel is utilized.
When I prune the model,  [https://github.com/wlguan/Stronger-yolo-pytorch/blob/a42d88c4cc84c04bd3e8879da1727033f52a03ec/pruning/BasePruner.py#L37-L38](url), mergelarge.conv7 should start with "module."

By the way, when I use mobilenet v2 as backbone, what Prune.bbOutName should be?

**Comment by wlguan** [comment]
@ArsenLuca Check [this](https://github.com/wlguan/Stronger-yolo-pytorch/blob/master/configs/strongerv3_prune.yaml#L44-L44) for bbOutName.

**Comment by ArsenLuca** [comment]
> @ArsenLuca Check [this](https://github.com/wlguan/Stronger-yolo-pytorch/blob/master/configs/strongerv3_prune.yaml#L44-L44) for bbOutName.

Thanks, it works (After inserting module. prefix).
