### ISSUE TITLE
where is the KL-loss code

### ISSUE THREAD

**Issue by changxinC** [wlguan/Stronger-yolo-pytorch#23]
I want to add your kl-loss to my model, but I can't find which script file you put your code on. Can you put a link here? Thank you

**Comment by wlguan** [comment]
@changxinC Hi, you'd better run the whole [experiment](https://github.com/wlguan/Stronger-yolo-pytorch/blob/master/configs/strongerv3_kl.yaml). The related codes are in file **strongerv3kl.py** and **yololoss.py**.
