### ISSUE TITLE
mobilenetv2_0.75.pth是否有问题？

### ISSUE THREAD

**Issue by TOM-tym** [wlguan/Stronger-yolo-pytorch#27]
感谢作者的付出，模型很赞。
我在百度云下载了strongerv3_0.75.pth，置于checkpoints下，但是在我尝试使用strongerv3_0.75.yaml进行训练的时候
`python main.py --config-file configs/strongerv3_0.75.yaml  EXPER.experiment_name strongerv3_0.75 devices 0,`
会出现错误

> Traceback (most recent call last):
  File "main.py", line 44, in <module>
    main(args=cfg)
  File "main.py", line 12, in main
    net = eval(cfg.MODEL.modeltype)(cfg=args.MODEL).cuda()
  File "/home/tom/tangym/Stronger-yolo-pytorch/models/strongerv3.py", line 11, in __init__
    self.backbone = eval(cfg.backbone)(pretrained=cfg.backbone_pretrained)
  File "/home/tom/tangym/Stronger-yolo-pytorch/models/backbone/mobilev2.py", line 96, in mobilenetv2_75
    load_mobilev2(model,pretrained)
  File "/home/tom/tangym/Stronger-yolo-pytorch/models/backbone/helper.py", line 13, in load_mobilev2
    model.load_state_dict(newstatedict)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MobileNetV2:
	size mismatch for features.1.conv.dw_conv.weight: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([24, 1, 3, 3]).
	size mismatch for features.1.conv.dw_bn.weight: copying a param with shape torch.Size([24, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.1.conv.project_conv.weight: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([16, 24, 1, 1]).
	size mismatch for features.1.conv.project_bn.weight: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for features.1.conv.project_bn.bias: copying a param with shape torch.Size([16, 24, 1, 1]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for features.2.conv.expand_conv.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([96, 16, 1, 1]).
	size mismatch for features.2.conv.expand_bn.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([96]).
	size mismatch for features.2.conv.expand_bn.bias: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([96]).
	size mismatch for features.2.conv.expand_bn.running_mean: copying a param with shape torch.Size([96, 16, 1, 1]) from checkpoint, the shape in current model is torch.Size([96]).
	size mismatch for features.2.conv.dw_conv.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([96, 1, 3, 3]).
	size mismatch for features.2.conv.dw_bn.running_mean: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([96]).
	size mismatch for features.2.conv.dw_bn.running_var: copying a param with shape torch.Size([96, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([96]).
	size mismatch for features.2.conv.project_conv.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([24, 96, 1, 1]).
	size mismatch for features.2.conv.project_bn.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.2.conv.project_bn.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.2.conv.project_bn.running_mean: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.2.conv.project_bn.running_var: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.3.conv.expand_conv.weight: copying a param with shape torch.Size([24, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([144, 24, 1, 1]).
	size mismatch for features.3.conv.expand_bn.weight: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.3.conv.expand_bn.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.3.conv.expand_bn.running_mean: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.3.conv.expand_bn.running_var: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.3.conv.dw_conv.weight: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([144, 1, 3, 3]).
	size mismatch for features.3.conv.dw_bn.weight: copying a param with shape torch.Size([144, 24, 1, 1]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.3.conv.project_conv.weight: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([24, 144, 1, 1]).
	size mismatch for features.3.conv.project_bn.weight: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.3.conv.project_bn.bias: copying a param with shape torch.Size([144, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.3.conv.project_bn.running_mean: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.3.conv.project_bn.running_var: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.4.conv.expand_conv.weight: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([144, 24, 1, 1]).
	size mismatch for features.4.conv.expand_bn.bias: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.4.conv.expand_bn.running_mean: copying a param with shape torch.Size([24, 144, 1, 1]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.4.conv.expand_bn.running_var: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.4.conv.dw_conv.weight: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([144, 1, 3, 3]).
	size mismatch for features.4.conv.dw_bn.weight: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.4.conv.dw_bn.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.4.conv.dw_bn.running_mean: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.4.conv.dw_bn.running_var: copying a param with shape torch.Size([144, 24, 1, 1]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.4.conv.project_conv.weight: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([24, 144, 1, 1]).
	size mismatch for features.4.conv.project_bn.weight: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.4.conv.project_bn.bias: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.4.conv.project_bn.running_mean: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.4.conv.project_bn.running_var: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.5.conv.expand_conv.weight: copying a param with shape torch.Size([144, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([144, 24, 1, 1]).
	size mismatch for features.5.conv.dw_conv.weight: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([144, 1, 3, 3]).
	size mismatch for features.5.conv.dw_bn.weight: copying a param with shape torch.Size([24, 144, 1, 1]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.5.conv.dw_bn.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.5.conv.dw_bn.running_mean: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.5.conv.dw_bn.running_var: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.5.conv.project_conv.weight: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([24, 144, 1, 1]).
	size mismatch for features.5.conv.project_bn.weight: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.5.conv.project_bn.bias: copying a param with shape torch.Size([144, 24, 1, 1]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.5.conv.project_bn.running_mean: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.5.conv.project_bn.running_var: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for features.6.conv.expand_conv.weight: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([144, 24, 1, 1]).
	size mismatch for features.6.conv.expand_bn.bias: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.6.conv.expand_bn.running_mean: copying a param with shape torch.Size([144, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.6.conv.dw_conv.weight: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([144, 1, 3, 3]).
	size mismatch for features.6.conv.dw_bn.running_mean: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for features.6.conv.dw_bn.running_var: copying a param with shape torch.Size([24, 144, 1, 1]) from checkpoint, the shape in current model is torch.Size([144]).
………………………………

等等的错误，是否是因为预训练权重文件有问题呢？
谢谢！

**Comment by wlguan** [comment]
@TOM-tym 请问使用的是哪个版本的pytorch

**Comment by TOM-tym** [comment]
Pytorch版本是1.12.0
@wlguan

**Comment by wlguan** [comment]
@TOM-tym 我没看懂你的问题，百度云里只有mobilenetv2_0.75.pth。  建议你用下面的代码检查一下model和checkpoint是否一致，注意先把num_batches_tracked去掉
for (k1,v1),(k2,v2) in zip(model.state_dict().items(),ckpt.state_dict().items()):
        print(k1,k2)

**Comment by TOM-tym** [comment]
@wlguan ,抱歉，我指的是mobilenetv2_0.75.pth，标题已修改

**Comment by TOM-tym** [comment]
@wlguan 当我使用
`net = eval(cfg.MODEL.modeltype)(cfg=args.MODEL).cuda()`
生成模型并导入权重的时候，仍然出现上述的错误。

**Comment by wlguan** [comment]
@TOM-tym 百度云里的其他checkpoint试一下，都不行吗？

**Comment by TOM-tym** [comment]
@wlguan 
我只尝试过mobilenetv2和mobilenetv2_0.75，其中mobilenetv2_0.75这个权重不行。
model.state_dict().items()和ckpt.items())是完全一致的，但是仍然无法运行，参见我上面的错误，发现报错的层数需要的维度总是和上一层相同。e.g.

> size mismatch for features.1.conv.dw_conv.weight: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([24, 1, 3, 3]).
size mismatch for features.1.conv.dw_bn.weight: copying a param with shape torch.Size([24, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([24]).

遂怀疑是否是num_batches_tracked没有去除？
查看models/backbone/helper.py [8到12行](https://github.com/wlguan/Stronger-yolo-pytorch/blob/master/models/backbone/helper.py#L8-L12)
发现仅对net中的num_batches_tracked进行了pop操作而没有对checkpoint进行pop。
```python
for k,v in model.state_dict().items():
         if 'num_batches_tracked' in k:
             statedict.pop(k)
```
而后的代码
```python
for idx,((k,v),(k2,v2)) in enumerate(zip(statedict.items(),weights.items())):
        newstatedict.update({k:v2})
```
却又将已经去除num_batches_tracked的statedict和未去除num_batches_tracked的weights构造一个新orderdict，认为问题出现在这里。
如果在update这个循环的上面加入checkpoint进行pop的代码，
```python
temp = weights.copy()
for k,v in weights.items():
        if 'num_batches_tracked' in k:
            weights.pop(k)
```
则可以正常导入权重并训练。但是不知道会不会存在其他问题。
请问作者这里是否存在我说的问题？谢谢！

**Comment by wlguan** [comment]
@TOM-tym 不好意思，是我传预训练权重的时候传错了，应该是传去掉num_batches_tracked的，百度云已更新。这里建议load的时候去掉num_batches_tracked，因为mobilev2的模型可能是从tf直接倒过来的，num_batches_tracked是pytorch独有的。

**Comment by TOM-tym** [comment]
@wlguan 辛苦，感谢解答，那我把issue关闭了。
