### ISSUE TITLE
how can i train my own data using yolov3 with all tricks in the latest papers?

### ISSUE THREAD

**Issue by oceanzm1992** [wlguan/Stronger-yolo-pytorch#28]
hello, i have a question. i saw in the Usage.md that you gave the instruction how to train a model using  
strongerv3 with mobilenet, if i want to change the backbone net to Darknet 53, should i use configs/strongerv1.yaml and change the strongerv1.yaml like strongerv3_all.yaml? So i can use all the training tricks like KL loss and ASFF model. I didn't wheather this was right.
I'm looking forward to your reply. Thank you!

**Comment by wlguan** [comment]
Hi, @oceanzm1992. Yes, simply modify the config file to add the module you want.
