### ISSUE TITLE
为什么我测试你百度云的strongerv3_all，mAP:0.7263549015277921，和你给出的81.1差距非常大

### ISSUE THREAD

**Issue by hyaihjq** [wlguan/Stronger-yolo-pytorch#29]

**Comment by wlguan** [comment]
LOG:
successfully load ckpt mobilev2
successfully load checkpoint bestt
mAP:0.811061277147463
AP@aeroplane:0.8793127569589401
AP@bicycle:0.868756659736112
AP@bird:0.8062431359564248
AP@boat:0.7159230262628445
AP@bottle:0.6956738511801079
AP@bus:0.9187710557786297
AP@car:0.904287653268232
AP@cat:0.8934592970170507
AP@chair:0.5949000912242741
AP@cow:0.8798117616901412
AP@diningtable:0.7250768953163085
AP@dog:0.8730893595047271
AP@horse:0.9073817709075925
AP@motorbike:0.8724607287800932
AP@person:0.851239956335658
AP@pottedplant:0.5581073834740118
AP@sheep:0.8113439011150247
AP@sofa:0.8006276610102339
AP@train:0.8662457438111875
AP@tvmonitor:0.798512853621665

可以做如下检查：
1.是否测试了所有5000张图片
2.后处理配置是否修改
3.百度云其他ckpt是否有问题

**Comment by hyaihjq** [comment]
sorry，我重新git代码，测试正常了，和你的结果一样，我找下原因，谢谢！！！可能我改了某些代码导致的，我再看看到底问题出在哪。

**Comment by hyaihjq** [comment]
我将difficult.append(int(t.find("difficult").text))改成了difficult.append(0)导致的
