### ISSUE TITLE
load_checkpoint:  'dict' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by jerryho-quanta** [wlguan/Stronger-yolo-pytorch#3]
Hi wlguan,

Could you help this python error?
when I use 
python main.py --config-file configs/voc.yaml EXPER.resume best  do_test True EXPER.experiment_name voc_512 devices 0,1,
or
python main_prune.py --config-file configs/voc_prune.yaml  EXPER.experiment_name voc_512_sparse Prune.sparse True Prune.pruneratio 0.3

I meet this python error,
"/home/jerry/anaconda3/envs/pytorch/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 154, in load_checkpoint
    if filename.startswith('modelzoo://'):
AttributeError: 'dict' object has no attribute 'startswith'

Thanks,

Jerry

**Comment by wlguan** [comment]
@jerryho-quanta I commented several lines related to modelzoo:// in mmcv.  You can use this code instead. 
 [self.model.load_state_dict(ckptfile['state_dict'])] 
 Sorry for the confusion.

**Comment by wlguan** [comment]
Fixed.
