### ISSUE TITLE
the code have two problem

### ISSUE THREAD

**Issue by hyaihjq** [wlguan/Stronger-yolo-pytorch#30]
1、在测试的时候改变batch_size，测试的结果会改变，而且变化不小；
２、多ＧＰＵ训练（devices 0,１）的模型用单ＧＰＵ测试（devices 0,）会出错，单ＧＰＵ训练的模型用多ＧＰＵ测试也会出错，原因为torch.nn.DataParallel导致，如何优雅的解决这两个问题呢？

**Comment by wlguan** [comment]
1. 能具体给出测试哪一个模型，包括具体结果改变的情况吗？
2. 可以简单像下面修改
            ckptfile = torch.load(os.path.join(self.save_path, 'checkpoint-{}.pth'.format(self.args.EXPER.resume)))
            # take care of the distributed model
            if 'module.' in list(self.model.state_dict().keys())[0]:
                newdict=OrderedDict()
                for k,v in ckptfile['state_dict'].items():
                    if 'module.' not in k:
                        newdict['module.'+k]=v
                    else:
                        newdict[k]=v
                ckptfile['state_dict']=newdict
            self.model.load_state_dict(ckptfile['state_dict'])

**Comment by hyaihjq** [comment]
针对１是我自己的数据训练的模型，我只是改变了batch_size，您可以试试你的VOC模型，或者等我有时间我在VOC上测一下告诉你

**Comment by wlguan** [comment]
我测了stronger_v3的某个实验。结果如下：
batchsize 12：0.7919
batchsize 6：0.7920
batchsize 2：0.7918
至于为什么会有微小差异我也不清楚，如果你的实验差距很大可以保存Evaluator中的rec_pred，比较前后哪些图片的结果有差异。

**Comment by hyaihjq** [comment]
好的，我找找原因，谢谢

**Comment by hyaihjq** [comment]
感觉是BN层导致的，作者可以研究下

**Comment by wlguan** [comment]
> 感觉是BN层导致的，作者可以研究下

你是指统计参数吗？.eval()操作之后BN层应该就不更新running_mean和running_var了

**Comment by hyaihjq** [comment]
我的数据集训练的模型，batch size16和１差距1.3mAP，很奇怪

**Comment by hyaihjq** [comment]
`ckptfile = torch.load(os.path.join(self.save_path, 'checkpoint-{}.pth'.format(self.args.EXPER.resume)))
            # (hy)
            # take care of the distributed model
            # solve the error of {multi gpu train, one gpu test} or {one gpu train, multi gpu test} cause by "torch.nn.DataParallel"
            if 'module.' in list(self.model.state_dict().keys())[0]:
                from collections import OrderedDict
                newdict = OrderedDict()
                for k, v in ckptfile['state_dict'].items():
                    if 'module.' not in k:
                        newdict['module.' + k] = v
                    else:
                        newdict[k] = v
                ckptfile['state_dict'] = newdict
            else:
                from collections import OrderedDict
                newdict = OrderedDict()
                for k, v in ckptfile['state_dict'].items():
                    if 'module.' in k:
                        newdict[k.replace('module.','')] = v
                    else:
                        newdict[k] = v
                ckptfile['state_dict'] = newdict
            # (hy_end)
            self.model.load_state_dict(ckptfile['state_dict'])`

**Comment by hyaihjq** [comment]
`ckptfile = torch.load(os.path.join(self.save_path, 'checkpoint-{}.pth'.format(self.args.EXPER.resume)))
            # (hy)
            # take care of the distributed model
            # solve the error of {multi gpu train, one gpu test} or {one gpu train, multi gpu test} cause by "torch.nn.DataParallel"
            if 'module.' in list(self.model.state_dict().keys())[0]:
                from collections import OrderedDict
                newdict = OrderedDict()
                for k, v in ckptfile['state_dict'].items():
                    if 'module.' not in k:
                        newdict['module.' + k] = v
                    else:
                        newdict[k] = v
                ckptfile['state_dict'] = newdict
            else:
                from collections import OrderedDict
                newdict = OrderedDict()
                for k, v in ckptfile['state_dict'].items():
                    if 'module.' in k:
                        newdict[k.replace('module.','')] = v
                    else:
                        newdict[k] = v
                ckptfile['state_dict'] = newdict
            # (hy_end)
            self.model.load_state_dict(ckptfile['state_dict'])`
你上面的代码只能解决单GPU训练的模型多GPU测试，这个可以解决多GPU训练单GPU测试

**Comment by hyaihjq** [comment]
当batch size训练和测试时相同时，结果最好，不同时不论过小或者过大都会下降
