### ISSUE TITLE
how to use the images contains no objects?

### ISSUE THREAD

**Issue by phucnhs** [wlguan/Stronger-yolo-pytorch#34]

**Comment by wlguan** [comment]
For what purpose? Training or Inference?

**Comment by phucnhs** [comment]
i want to ask for training ,i see  yolov3 darknet has support use image contains no object for training .
Is there any way to add it .

**Comment by wlguan** [comment]
@phucnhs Just prepare a corresponding xml file with no objects

**Comment by phucnhs** [comment]
thanks you , i will try it
