### ISSUE TITLE
最新的代码分布式训练，VOC mAP只有0.3516

### ISSUE THREAD

**Issue by hyaihjq** [wlguan/Stronger-yolo-pytorch#35]

**Comment by wlguan** [comment]
麻烦贴出config文件，最好配上tensorboard训练过程

**Comment by hyaihjq** [comment]
![微信截图_20200316180134](https://user-images.githubusercontent.com/27874026/76745164-59fed780-67b0-11ea-982a-51eee3799388.png)

**Comment by hyaihjq** [comment]
最新的代码，只改了数据路径，命令：python main_dist.py --config-file configs/strongerv3.yaml  EXPER.experiment_name strongerv3 ngpu 2，结果和上次一样，mAP依然很低

**Comment by hyaihjq** [comment]
目前代码，在VOC数据集上结果比之前低很多

**Comment by WallZFE** [comment]
你可以修改batch_size，epoch和学习率，可以提高map。我这边把OPTIM.batch_size设置为32，OPTIM.lr_initial设置为0.001，OPTIM.total_epoch设置为300，OPTIM.milestones 设置为 [50,120,200]。跑到了140多epoch，map达到了62%，后面没时间跑了就停止训练了。

**Comment by wlguan** [comment]
@WallZFE  batch size 32? 每张卡都放32个batch放得下吗？请问多大的显存？

**Comment by wlguan** [comment]
@hyaihjq   如果真的觉得是分布式代码的问题，可以使用ngpu=1的单卡训练，和之前的代码是完全一样的。

**Comment by WallZFE** [comment]
@wlguan 我这边batch_size为32，显存差不多使用16G，是有点多

**Comment by hyaihjq** [comment]
> 但是根据你放出的图看，显然是没有训练到收敛。

好的，我在看看，谢谢
