### ISSUE TITLE
auto slim result now is bad than slimming？

### ISSUE THREAD

**Issue by zyc4me** [wlguan/Stronger-yolo-pytorch#37]

**Comment by wlguan** [comment]
Note that  the inplace-distillation  of autoslim is not implemented.
According to my results, slimming is more suitable for the detection task. But for classification, you may see another [repo](https://github.com/wlguan/MobileNet-v2-pruning) of mine.

**Comment by zyc4me** [comment]
> Note that the inplace-distillation of autoslim is not implemented.
> According to my results, slimming is more suitable for the detection task. But for classification, you may see another [repo](https://github.com/wlguan/MobileNet-v2-pruning) of mine.

many thanks
