### ISSUE TITLE
真实坐标框的处理

### ISSUE THREAD

**Issue by WallZFE** [wlguan/Stronger-yolo-pytorch#38]
您好，我看你的 strongerv3.py 文件里，在yolo_target_single函数写了reg_area_limit = [0, 30, 90, 10000]，这样做的目的是不是保证每个真实的坐标框只落在一个特征图里。那我想问一下30 ，90是怎么取的，有什么参考的资料吗？

**Comment by wlguan** [comment]
@WallZFE 你好，对于anchor free的算法无法通过与anchor IOU匹配的方式进行FPN分层，这里是类似fcos人为选取的数值，可以理解为一个超参数，但不是非常敏感。如果小于30，就放在FPN浅层，因为这里receptive field比较小。我也在探索有没有更好的方式。

**Comment by WallZFE** [comment]
嗯嗯，谢谢您
