### ISSUE TITLE
train coco with darknet53 ...and instances_val2017_nocls.json?

### ISSUE THREAD

**Issue by jerryho-quanta** [wlguan/Stronger-yolo-pytorch#4]
Hi wlguan,

I am trying to prune yolov3 with darknet53 using coco dataset

(1) it seems that this git use mobilenetv2?
Could it be applied for darknet53?
Could I just replace darknet53.pth ?

(2) what is instances_val2017_nocls? Where could I get if I want to train coco2014 version?
python main.py --config-file configs/coco.yaml  EXPER.experiment_name coco512_sparse Prune.sparse True Prune.sr 0.01
args.MODEL is LABEL: ['person', 'bicycle', 'car', 'motorbike', 'aeroplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'sofa', 'pottedplant', 'bed', 'diningtable', 'toilet', 'tvmonitor', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']
boxloss: iou
clsfocal: False
gt_per_grid: 3
l1scale: 1.0
modeltype: YoloV3
numcls: 80
seprelu: True
successfully load ckpt mobilev2
loading annotations into memory...
creating index...
index created!
Done (t=4.74s)
loading annotations into memory...
creating index...
index created!
Done (t=10.97s)
loading annotations into memory...
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    main(args=cfg)
  File "main.py", line 20, in main
    lrscheduler=scheduler
  File "/home/data/Stronger-yolo-pytorch/trainers/trainer_coco.py", line 6, in __init__
    super().__init__(args, model, optimizer,lrscheduler)
  File "/home/data/Stronger-yolo-pytorch/trainers/base_trainer.py", line 54, in __init__
    self._get_loggers()
  File "/home/data/Stronger-yolo-pytorch/trainers/trainer_coco.py", line 15, in _get_loggers
    iou_thres=0.5,
  File "/home/data/Stronger-yolo-pytorch/evaluator/cocoeval.py", line 96, in __init__
    super().__init__(anchors, cateNames, rootpath, score_thres, iou_thres)
  File "/home/data/Stronger-yolo-pytorch/evaluator/Evaluator.py", line 19, in __init__
    self.build_GT()
  File "/home/data/Stronger-yolo-pytorch/evaluator/cocoeval.py", line 105, in build_GT
    self.cocoGt = COCO(os.path.join(self.dataset_root, 'annotations/instances_val2014_nocls.json'))
  File "/home/data/Stronger-yolo-pytorch/dataset/pycocotools/coco.py", line 85, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/Lam-YOLOv3-model-pruning/data/coco/annotations/**instances_val2014_nocls.json**'

Thanks,

Jerry

**Comment by wlguan** [comment]
@jerryho-quanta Hi,Jerry. 
(1) Currently darknet53 is not supported.  You can't just replace the backbone since corresponding layer haven't been supported in [BaseLayer ](https://github.com/wlguan/Stronger-yolo-pytorch/blob/master/pruning/Block.py), but it should be easy since most layers are [class CB](https://github.com/wlguan/Stronger-yolo-pytorch/blob/master/pruning/Block.py#L35-L54). I might support it this weekend or you can do it yourself.
(2) It's a custom coco annotation which is class-agnostic. Replace it with instances_val2014.json will do fine. Sorry for the confusion.

**Comment by wlguan** [comment]
Darknet supported.
