### ISSUE TITLE
Why is the mAP version lower the tensorflow version?

### ISSUE THREAD

**Issue by simon-rob** [wlguan/Stronger-yolo-pytorch#7]
Why does your version have a lower mAP:

76.5 compared to 88

Regards,

Simon

**Comment by wlguan** [comment]
@simon-rob Hi, I only implemented YOLOV3-Lite(backbone is mobilenetv2), which is 79.4 in tensorflow version. But I only trained the network for 60 epochs(maybe 100 epochs in the original implementation) and tested with confindence threshold 0.1 to make make the whole process faster.

**Comment by wlguan** [comment]
@simon-rob The latest code in master branch has supported strongeryolov1/v2. Later I will update the corresponding results.

**Comment by wlguan** [comment]
@simon-rob Results updated in models/MODELZOO.md.
