### ISSUE TITLE
modify backbone

### ISSUE THREAD

**Issue by CuongNguyen218** [wlguan/Stronger-yolo-pytorch#8]
Hi @wlguan ,
i want to modify yolov3 with another backbone. How can I do that ? Can you guide me?

**Comment by CuongNguyen218** [comment]
Beside that, how can I train baseline without GIOU ?

**Comment by wlguan** [comment]
Hi, @CuongNguyen218
(1)currently 2 backbones are supported, Darknet53 and MobileNetV2. You can define your own backbone under models/backbone.py and specify output channels like [this](https://github.com/wlguan/Stronger-yolo-pytorch/blob/master/models/backbone/darknet.py/#L10-L10). After that modify a new config file to build your new model. See configs/strongv1.yaml and configs/strongv3.yaml for more details.
(2) Simply modify the [loss config](https://github.com/wlguan/Stronger-yolo-pytorch/blob/master/yacscfg.py#L17-L17), currently smoothL1 and KLloss are supported. If you use L1 loss, I would recommend _C.MODEL.l1scale = 0.01.
