### ISSUE TITLE
Pruning fails with MobileNetv2 backbone

### ISSUE THREAD

**Issue by simon-rob** [wlguan/Stronger-yolo-pytorch#9]
I am following the instructions to tune, but I get :

Traceback (most recent call last):
```
  File "main_prune.py", line 95, in <module>
    main(args=cfg).run()
  File "main_prune.py", line 58, in main
    pruner.prune()
  File "/hdd1/Stronger-yolo-pytorch/head/Stronger-yolo-pytorch/pruning/slimming.py", line 12, in prune
    super().prune()
  File "/hdd1/Stronger-yolo-pytorch/head/Stronger-yolo-pytorch/pruning/BasePruner.py", line 41, in prune
    b.inputlayer.append(name2layer[self.args.bbOutName[1]])
KeyError: 'backbone.layer4.residual_7'
```

self.blocks in BasePrunner.py contains:

`[CB(name=backbone.features.0, id=1, numweights=5,inchannel=3,outchannel=32), InverRes(name=backbone.features.1, id=2, numweights=10,inchannel=1,outchannel=16), InverRes(name=backbone.features.2, id=3, numweights=15,inchannel=16,outchannel=24), InverRes(name=backbone.features.3, id=4, numweights=15,inchannel=24,outchannel=24), InverRes(name=backbone.features.4, id=5, numweights=15,inchannel=24,outchannel=32), InverRes(name=backbone.features.5, id=6, numweights=15,inchannel=32,outchannel=32), InverRes(name=backbone.features.6, id=7, numweights=15,inchannel=32,outchannel=32), InverRes(name=backbone.features.7, id=8, numweights=15,inchannel=32,outchannel=64), InverRes(name=backbone.features.8, id=9, numweights=15,inchannel=64,outchannel=64), InverRes(name=backbone.features.9, id=10, numweights=15,inchannel=64,outchannel=64), InverRes(name=backbone.features.10, id=11, numweights=15,inchannel=64,outchannel=64), InverRes(name=backbone.features.11, id=12, numweights=15,inchannel=64,outchannel=96), InverRes(name=backbone.features.12, id=13, numweights=15,inchannel=96,outchannel=96), InverRes(name=backbone.features.13, id=14, numweights=15,inchannel=96,outchannel=96), InverRes(name=backbone.features.14, id=15, numweights=15,inchannel=96,outchannel=160), InverRes(name=backbone.features.15, id=16, numweights=15,inchannel=160,outchannel=160), InverRes(name=backbone.features.16, id=17, numweights=15,inchannel=160,outchannel=160), InverRes(name=backbone.features.17, id=18, numweights=15,inchannel=160,outchannel=320), CB(name=backbone.features.18, id=19, numweights=5,inchannel=320,outchannel=1280), CB(name=headslarge.conv0, id=20, numweights=5,inchannel=1280,outchannel=512), DCB(name=headslarge.conv1, id=21, numweights=10,inchannel=512,outchannel=1024), CB(name=headslarge.conv2, id=22, numweights=5,inchannel=1024,outchannel=512), DCB(name=headslarge.conv3, id=23, numweights=10,inchannel=512,outchannel=1024), CB(name=headslarge.conv4, id=24, numweights=5,inchannel=1024,outchannel=512), DCB(name=detlarge.conv5, id=25, numweights=10,inchannel=512,outchannel=1024), Conv(name=detlarge.conv6, id=26, numweights=2,inchannel=1024,outchannel=36), CB(name=mergelarge.conv7, id=27, numweights=5,inchannel=512,outchannel=256), CB(name=headsmid.conv8, id=28, numweights=5,inchannel=352,outchannel=256), DCB(name=headsmid.conv9, id=29, numweights=10,inchannel=256,outchannel=512), CB(name=headsmid.conv10, id=30, numweights=5,inchannel=512,outchannel=256), DCB(name=headsmid.conv11, id=31, numweights=10,inchannel=256,outchannel=512), CB(name=headsmid.conv12, id=32, numweights=5,inchannel=512,outchannel=256), DCB(name=detmid.conv13, id=33, numweights=10,inchannel=256,outchannel=512), Conv(name=detmid.conv14, id=34, numweights=2,inchannel=512,outchannel=36), CB(name=mergemid.conv15, id=35, numweights=5,inchannel=256,outchannel=128), CB(name=headsmall.conv16, id=36, numweights=5,inchannel=160,outchannel=128), DCB(name=headsmall.conv17, id=37, numweights=10,inchannel=128,outchannel=256), CB(name=headsmall.conv18, id=38, numweights=5,inchannel=256,outchannel=128), DCB(name=headsmall.conv19, id=39, numweights=10,inchannel=128,outchannel=256), CB(name=headsmall.conv20, id=40, numweights=5,inchannel=256,outchannel=128), DCB(name=detsmall.conv21, id=41, numweights=10,inchannel=128,outchannel=256), Conv(name=detsmall.conv22, id=42, numweights=2,inchannel=256,outchannel=36)]`

I suspect the entry in the cfg is incorrect:
_C.Prune.bbOutName=('backbone.layer3.residual_7','backbone.layer4.residual_7','backbone.layer5.residual_3')

What should it be for a MobileNetV2 backbone?

Many thanks

**Comment by wlguan** [comment]
@simon-rob Hi, I forgot to upload the config file for v3 pruning(strongerv3_prune.yaml). You can check the latest master branch. In short, ('backbone.layer3.residual_7','backbone.layer4.residual_7','backbone.layer5.residual_3') is for darknet backbone, you need to replace with mobilev2 backbone outputs.
